- name: Install Kubernetes dependencies
  hosts: all
  become: true
  tasks:
    - name: Install required system packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - "apt-transport-https"
        - "ca-certificates"
        - "curl"
        - "software-properties-common"
        - "python3-pip"
        - "virtualenv"
        - "python3-setuptools"
      become: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
      become: true

    - name: Install Docker and Docker-Compose
      apt:
        pkg:
          - docker
          - docker-ce
          - docker-compose
        state: latest
        update_cache: yes
      become: true
      
    - name: Add current user to the docker group
      become: true
      shell: usermod -aG docker $USER

    # - name: Switch to the docker group
    #   become: true
    #   shell: newgrp docker


    - name: Create directory
      file:
        path: /jonathan/fitnessTracking/
        state: directory
        recurse: yes
        owner: jonathan

    - name: Copy Docker Compose File
      copy:
        src: ./docker-compose.yaml
        dest: fitnessTracking/

    - name: Run Docker Container
      shell: |
        docker compose -f fitnessTracking/docker-compose.yaml pull
        docker compose -f fitnessTracking/docker-compose.yaml up -d

