---
- name: Deploy Java Web Application
  hosts: your_target_hosts
  become: true
  vars:
    app_name: "FitnessTracking"
    app_version: "1.0"
    app_port: 8080
    app_war_file: "FitnessTracking.war"

  tasks:
    - name: Ensure Java is installed
      become: true
      apt:
        name: openjdk-11-jdk
        state: present
      tags: [java]

    - name: Copy WAR file to the server
      copy:
        src: /path/to/your/FitnessTracking.war
        dest: /opt/{{ app_name }}/{{ app_war_file }}

    - name: Start the Java application
      command: "java -jar /opt/{{ FitnessTracking }}/{{ FitnessTracking }}"
      async: 60
      poll: 0
      ignore_errors: yes
