version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Using Java 8 image

    working_directory: ~/app  # Set your project directory

    steps:
      - checkout  # Check out the code from the repository

      - run:
          name: Set up JDK 8
          command: |
            sudo update-java-alternatives -s java-1.8.0-openjdk-amd64

      - run:
          name: Install dependencies and build
          command: mvn clean install  # Use Maven to clean and install dependencies

      - run:
          name: Run tests
          command: mvn test  # Run tests using Maven
