apiVersion: v1
kind: Service
metadata:
  name: fitness-tracking-service
spec:
  type: NodePort
  selector:
    app: fitness-tracking
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
