version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/app

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "pom.xml" }}
      
      - run:
          name: Download Dependencies
          command: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: jars-{{ checksum "pom.xml" }}

      - run:
          name: Run Tests
          command: mvn test

      - store_test_results:
          path: target/surefire-reports
          destination: surefire-reports

      - store_artifacts:
          path: target/site/jacoco/
          destination: jacoco-report

workflows:
  version: 2
  build:
    jobs:
      - build
